### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by tuuusel** [electerious/formbase#10]
Hi there. 
Sorry to bother but we were wondering - what about input error feedback? 
Ty!

**Comment by electerious** [comment]
formbase only includes styles to ensure that form elements look the same on all browsers. Error styles aren't planned, but you can add custom ones on top of formbase.

**Comment by tuuusel** [comment]
Hi there thank you for getting back to me. 
any guideline / suggestion on how to format those for formbase?

ty.

**Comment by electerious** [comment]
That depends on how you like it. You can add an `error` class to your inputs and simply apply styles on top of formbase. Just pretend there's no formbase and style how you would style a normal input.
